apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Chart.Name }}
rules:
  - apiGroups: ["github.krateo.io"]
    resources: ["repoes"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  
  - apiGroups: ["github.krateo.io"]
    resources: ["repoes/status"]
    verbs: ["get", "patch", "update"]
  
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
  
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch", "update"]