apiVersion: github.krateo.io/v1alpha1
kind: TeamRepo
metadata:
  name: github-provider-teamrepo
spec:
  apiUrl: https://api.github.com
  verbose: false
  credentials:
    secretRef:
      namespace: default
      name: github-secret
      key: token
  org: krateoplatformops
  owner: krateoplatformops
  teamSlug: testteam
  repo: demo-repo-poc
  permission: admin
